export const ARTIST_DASHBOARD_BOOK_START_REQUEST = 'ARTIST_DASHBOARD_BOOK_START_REQUEST';
export const ARTIST_DASHBOARD_BOOK_START_SUCCESS = 'ARTIST_DASHBOARD_BOOK_START_SUCCESS';
export const ARTIST_DASHBOARD_BOOK_START_FAIL = 'ARTIST_DASHBOARD_BOOK_START_FAIL';
export const ARTIST_DASHBOARD_BOOK_START_RESET = 'ARTIST_DASHBOARD_BOOK_START_RESET';

export const ARTIST_DASHBOARD_BOOK_END_REQUEST = 'ARTIST_DASHBOARD_BOOK_END_REQUEST';
export const ARTIST_DASHBOARD_BOOK_END_SUCCESS = 'ARTIST_DASHBOARD_BOOK_END_SUCCESS';
export const ARTIST_DASHBOARD_BOOK_END_FAIL = 'ARTIST_DASHBOARD_BOOK_END_FAIL';
export const ARTIST_DASHBOARD_BOOK_END_RESET = 'ARTIST_DASHBOARD_BOOK_END_RESET';

export const ARTIST_DASHBOARD_BOOK_CANCEL_REQUEST = 'ARTIST_DASHBOARD_BOOK_CANCEL_REQUEST';
export const ARTIST_DASHBOARD_BOOK_CANCEL_SUCCESS = 'ARTIST_DASHBOARD_BOOK_CANCEL_SUCCESS';
export const ARTIST_DASHBOARD_BOOK_CANCEL_FAIL = 'ARTIST_DASHBOARD_BOOK_CANCEL_FAIL';
export const ARTIST_DASHBOARD_BOOK_CANCEL_RESET = 'ARTIST_DASHBOARD_BOOK_CANCEL_RESET';
