export const ARTIST_ACCOUNT_DETAILS_REQUEST = 'ARTIST_ACCOUNT_DETAILS_REQUEST';
export const ARTIST_ACCOUNT_DETAILS_SUCCESS = 'ARTIST_ACCOUNT_DETAILS_SUCCESS';
export const ARTIST_ACCOUNT_DETAILS_FAIL = 'ARTIST_ACCOUNT_DETAILS_FAIL';
export const ARTIST_ACCOUNT_DETAILS_RESET = 'ARTIST_ACCOUNT_DETAILS_RESET';