export const CUSTOMER_ACCOUNT_DETAILS_REQUEST = 'CUSTOMER_ACCOUNT_DETAILS_REQUEST';
export const CUSTOMER_ACCOUNT_DETAILS_SUCCESS = 'CUSTOMER_ACCOUNT_DETAILS_SUCCESS';
export const CUSTOMER_ACCOUNT_DETAILS_FAIL = 'CUSTOMER_ACCOUNT_DETAILS_FAIL';
export const CUSTOMER_ACCOUNT_DETAILS_RESET = 'CUSTOMER_ACCOUNT_DETAILS_RESET';