export const ARTIST_ACCOUNT_PHOTO_EDIT_REQUEST = 'ARTIST_ACCOUNT_PHOTO_EDIT_REQUEST';
export const ARTIST_ACCOUNT_PHOTO_EDIT_SUCCESS = 'ARTIST_ACCOUNT_PHOTO_EDIT_SUCCESS';
export const ARTIST_ACCOUNT_PHOTO_EDIT_FAIL = 'ARTIST_ACCOUNT_PHOTO_EDIT_FAIL';
export const ARTIST_ACCOUNT_PHOTO_EDIT_RESET = 'ARTIST_ACCOUNT_PHOTO_EDIT_RESET';

export const ARTIST_ACCOUNT_PHOTO_REMOVE_REQUEST = 'ARTIST_ACCOUNT_PHOTO_REMOVE_REQUEST';
export const ARTIST_ACCOUNT_PHOTO_REMOVE_SUCCESS = 'ARTIST_ACCOUNT_PHOTO_REMOVE_SUCCESS';
export const ARTIST_ACCOUNT_PHOTO_REMOVE_FAIL = 'ARTIST_ACCOUNT_PHOTO_REMOVE_FAIL';
export const ARTIST_ACCOUNT_PHOTO_REMOVE_RESET = 'ARTIST_ACCOUNT_PHOTO_REMOVE_RESET';
