export const ARTIST_ACCOUNT_NAME_EDIT_REQUEST = 'ARTIST_ACCOUNT_NAME_EDIT_REQUEST';
export const ARTIST_ACCOUNT_NAME_EDIT_SUCCESS = 'ARTIST_ACCOUNT_NAME_EDIT_SUCCESS';
export const ARTIST_ACCOUNT_NAME_EDIT_FAIL = 'ARTIST_ACCOUNT_NAME_EDIT_FAIL';
export const ARTIST_ACCOUNT_NAME_EDIT_RESET = 'ARTIST_ACCOUNT_NAME_EDIT_RESET';

