export const ARTIST_ACCOUNT_ACTIVATION_REQUEST = 'ARTIST_ACCOUNT_ACTIVATION_REQUEST';
export const ARTIST_ACCOUNT_ACTIVATION_SUCCESS = 'ARTIST_ACCOUNT_ACTIVATION_SUCCESS';
export const ARTIST_ACCOUNT_ACTIVATION_FAIL = 'ARTIST_ACCOUNT_ACTIVATION_FAIL';
export const ARTIST_ACCOUNT_ACTIVATION_RESET = 'ARTIST_ACCOUNT_ACTIVATION_RESET';
