export const CUSTOMER_ACCOUNT_REMOVE_REQUEST = 'CUSTOMER_ACCOUNT_REMOVE_REQUEST';
export const CUSTOMER_ACCOUNT_REMOVE_SUCCESS = 'CUSTOMER_ACCOUNT_REMOVE_SUCCESS';
export const CUSTOMER_ACCOUNT_REMOVE_FAIL = 'CUSTOMER_ACCOUNT_REMOVE_FAIL';
export const CUSTOMER_ACCOUNT_REMOVE_RESET = 'CUSTOMER_ACCOUNT_REMOVE_RESET';
