export const BOOKING_ARTIST_LIST_REQUEST = 'BOOKING_ARTIST_LIST_REQUEST';
export const BOOKING_ARTIST_LIST_SUCCESS = 'BOOKING_ARTIST_LIST_SUCCESS';
export const BOOKING_ARTIST_LIST_FAIL = 'BOOKING_ARTIST_LIST_FAIL';
export const BOOKING_ARTIST_LIST_RESET = 'BOOKING_ARTIST_LIST_RESET';

export const BOOKING_ARTIST_DETAILS_REQUEST = 'BOOKING_ARTIST_DETAILS_REQUEST';
export const BOOKING_ARTIST_DETAILS_SUCCESS = 'BOOKING_ARTIST_DETAILS_SUCCESS';
export const BOOKING_ARTIST_DETAILS_FAIL = 'BOOKING_ARTIST_DETAILS_FAIL';
export const BOOKING_ARTIST_DETAILS_RESET = 'BOOKING_ARTIST_DETAILS_RESET';

export const BOOKING_CUSTOMER_DETAILS_REQUEST = 'BOOKING_CUSTOMER_DETAILS_REQUEST';
export const BOOKING_CUSTOMER_DETAILS_SUCCESS = 'BOOKING_CUSTOMER_DETAILS_SUCCESS';
export const BOOKING_CUSTOMER_DETAILS_FAIL = 'BOOKING_CUSTOMER_DETAILS_FAIL';
export const BOOKING_CUSTOMER_DETAILS_RESET = 'BOOKING_CUSTOMER_DETAILS_RESET';
