export const ARTIST_ACCOUNT_MOBILE_EDIT_REQUEST = 'ARTIST_ACCOUNT_MOBILE_EDIT_REQUEST';
export const ARTIST_ACCOUNT_MOBILE_EDIT_SUCCESS = 'ARTIST_ACCOUNT_MOBILE_EDIT_SUCCESS';
export const ARTIST_ACCOUNT_MOBILE_EDIT_FAIL = 'ARTIST_ACCOUNT_MOBILE_EDIT_FAIL';
export const ARTIST_ACCOUNT_MOBILE_EDIT_RESET = 'ARTIST_ACCOUNT_MOBILE_EDIT_RESET';

export const ARTIST_ACCOUNT_MOBILE_VERIFY_REQUEST = 'ARTIST_ACCOUNT_MOBILE_VERIFY_REQUEST';
export const ARTIST_ACCOUNT_MOBILE_VERIFY_SUCCESS = 'ARTIST_ACCOUNT_MOBILE_VERIFY_SUCCESS';
export const ARTIST_ACCOUNT_MOBILE_VERIFY_FAIL = 'ARTIST_ACCOUNT_MOBILE_VERIFY_FAIL';
export const ARTIST_ACCOUNT_MOBILE_VERIFY_RESET = 'ARTIST_ACCOUNT_MOBILE_VERIFY_RESET';