export const CUSTOMER_ACCOUNT_ACTIVATION_REQUEST = 'CUSTOMER_ACCOUNT_ACTIVATION_REQUEST';
export const CUSTOMER_ACCOUNT_ACTIVATION_SUCCESS = 'CUSTOMER_ACCOUNT_ACTIVATION_SUCCESS';
export const CUSTOMER_ACCOUNT_ACTIVATION_FAIL = 'CUSTOMER_ACCOUNT_ACTIVATION_FAIL';
export const CUSTOMER_ACCOUNT_ACTIVATION_RESET = 'CUSTOMER_ACCOUNT_ACTIVATION_RESET';
