export const CUSTOMER_ACCOUNT_NAME_EDIT_REQUEST = 'CUSTOMER_ACCOUNT_NAME_EDIT_REQUEST';
export const CUSTOMER_ACCOUNT_NAME_EDIT_SUCCESS = 'CUSTOMER_ACCOUNT_NAME_EDIT_SUCCESS';
export const CUSTOMER_ACCOUNT_NAME_EDIT_FAIL = 'CUSTOMER_ACCOUNT_NAME_EDIT_FAIL';
export const CUSTOMER_ACCOUNT_NAME_EDIT_RESET = 'CUSTOMER_ACCOUNT_NAME_EDIT_RESET';

