export const BOOKING_LOCATION = 'BOOKING_LOCATION';

export const BOOKING_SKILL = 'BOOKING_SKILL';

export const BOOKING_DATE_FREE_REQUEST = 'BOOKING_DATE_FREE_REQUEST';
export const BOOKING_DATE_FREE_SUCCESS = 'BOOKING_DATE_FREE_SUCCESS';
export const BOOKING_DATE_FREE_FAIL = 'BOOKING_DATE_FREE_FAIL';
export const BOOKING_DATE_FREE_RESET = 'BOOKING_DATE_FREE_RESET';

export const BOOKING_DAY = 'BOOKING_DAY';
export const BOOKING_TIME = 'BOOKING_TIME';
export const BOOKING_ARTIST = 'BOOKING_ARTIST';

export const BOOKING_ARTIST_REQUEST = 'BOOKING_ARTIST_REQUEST';
export const BOOKING_ARTIST_SUCCESS = 'BOOKING_ARTIST_SUCCESS';
export const BOOKING_ARTIST_FAIL = 'BOOKING_ARTIST_FAIL';
export const BOOKING_ARTIST_RESET = 'BOOKING_ARTIST_RESET';

export const BOOKING_SERVICE = 'BOOKING_SERVICE';
export const BOOKING_SERVICE_REMOVE_ALL = 'BOOKING_SERVICE_REMOVE_ALL';

export const BOOKING_SUBMIT_REQUEST = 'BOOKING_SUBMIT_REQUEST';
export const BOOKING_SUBMIT_SUCCESS = 'BOOKING_SUBMIT_SUCCESS';
export const BOOKING_SUBMIT_FAIL = 'BOOKING_SUBMIT_FAIL';
export const BOOKING_SUBMIT_RESET = 'BOOKING_SUBMIT_RESET';

