export const ARTIST_ACCOUNT_REMOVE_REQUEST = 'ARTIST_ACCOUNT_REMOVE_REQUEST';
export const ARTIST_ACCOUNT_REMOVE_SUCCESS = 'ARTIST_ACCOUNT_REMOVE_SUCCESS';
export const ARTIST_ACCOUNT_REMOVE_FAIL = 'ARTIST_ACCOUNT_REMOVE_FAIL';
export const ARTIST_ACCOUNT_REMOVE_RESET = 'ARTIST_ACCOUNT_REMOVE_RESET';
