export const ARTIST_DASHBOARD_BOOK_LIST_REQUEST = 'ARTIST_DASHBOARD_BOOK_LIST_REQUEST';
export const ARTIST_DASHBOARD_BOOK_LIST_SUCCESS = 'ARTIST_DASHBOARD_BOOK_LIST_SUCCESS';
export const ARTIST_DASHBOARD_BOOK_LIST_FAIL = 'ARTIST_DASHBOARD_BOOK_LIST_FAIL';
export const ARTIST_DASHBOARD_BOOK_LIST_RESET = 'ARTIST_DASHBOARD_BOOK_LIST_RESET';